---
#Dev: kuatercraft#0062(discord)
#Discord: https://discord.gg/zQ3SQ4zzN5
#Note:- it does not show wether the plugin enables or disables!!
enabled: true         
# Did you enabled me?
discord_webhook_url: "" 
# Put that bad boy token here xd
discord_webhook_name: "MCDC"  
# What should be the custom name for the bad boi
discord_webhook_override: false
#Should this override badboy? (Defualt will be false) 
discord_webhook_refresh: 1
# Delay in updating discord
send_console: true 
# Send console logs?
show_player_events: true 
# Tell when a player joins/leaves the server
enable_pings: true 
# Honor pinging from Minecraft chat in discord
...
